name: Build and publish

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g. 1.2.3)'
        required: true
        type: string

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml